name: Continuous Integration

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        python: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: LS
      shell: bash
      run: |
        echo "INCLUDE"
        ls -lah $(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
        echo "PARENT"
        ls -lah $(dirname $(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())"))
        echo "GRANDPARENT"
        ls -lah $(dirname $(dirname $(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")))
        echo "bin"
        ls -lah $(dirname $(dirname $(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")))/bin
        echo "lib"
        ls -lah $(dirname $(dirname $(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")))/lib
